language: ruby
rvm: 2.3.1
node_js: 6.3.1

script: echo hello

deploy:
  provider: heroku
  api_key:
    secure: "F+DKAXjV5PMcpPFJ/Qfk+5qpnSVC2Cvk2hCuyatbPuv3k9XDt5q2kCSEORJm5C9Q5Lrilw7NhoXESheEOc+kBvwbO4edNKatmevlXJ19SsTp1GWBviT+BEMa000AABEdsznlz8nNvwp2paqhu2A7/fDqUCd6lkHStsK2AGIfv21GOFsH9f3D74uAQkFRnrx5AWw4EnieqB/qAmbtW7XRDjreVvw/BP7KCa8T7EcTcuJfY4hkfZYwH7POodlwC4IeR91ws7CyxKY1OkjeFC6CRkAmUYPdvOjbkvCwuN4wXrdTd19oHyXy4ssEHYUKvk861lgacu/cg6foD+d3qxL5OyI3LJAHlguZ1y7p4ScEEmjvEt1pljEoZXUAGRkHqjpaiI4yNtDuuMo5gAJ7KRvx5Anwkv4VLr/SJWKyXeSqjHbXPI+z3MVTdi7gUgB+xaxQjUyswM63bZQZW2A/KWpCv0LrvucKZtQk7ik4LocwyUqPwUIQg1/4K0c4I4iiF17Bi/C1P8ilOlKmYcv7S4zvG3hHxO9/B5OgK3xxWEhe9WVlCJ63DlJhlC6mmmMP4nHItZukVUeHjBarg+TO947AnBe6XKx0ix5y4ydz2NTKkjuGgi4z0vmc2LeHBV6R7gANxzW1xA8vs9UccAL/5MfLedNfryqpp3b10VMXaZjqcJ4="
    # cs: secure: "LXTfsrT2b654YEql/WfNVmp7tlaH/4XoU6WRq1H9Fj5k8jQForWvVnPppqmhZehttNijlLfLpiu0RPHUf3f5g+SPLc9KW2g83605W+lvv+POJx4hMBBEeUPSvXOw87dtsUlQS7KFbnbQ/0O2bNZvGKrtmqjMZRS4XIEZwyZ3VEtWxAVk9jAqdkDgIIyL2nkFmJEOrU6U8a1f5mxAAw1zqb8F6HPuIl+wea+iwvQ9qbSCUvPBRZmJANmvnBOInPS46Stv26iCDdX1suITlkclpSII/fU0oIvC0yRxaIXN/Y6qN+eEeEjZi7tHnrHA/60+r6xBbsJT5xHbAa+DbkU+/zKjdG9V242chvTHF9C5p1XHCFrct9uf5mmW2/sz0cN1judQYskuh7xjnOu3jG+vfFSi8tQpjwkit6EXDL9nP3wXtszygyDjjsSHEESytLFY405nQ+HN29hKW0XNNB/mqGLjpRj+e7NsXxb/cE7jGLHyVLCv9KAsvT/G8t3q0kipYYy2t03ceP20J1Do/vrKZm3vZ1ztNr4CIABjIaJIL064u8TDZ1lbm9PvMuXwfpFYPj4k5F2WBvLMGE/h+mkarLE3m/5eyCCey03a1KXA1+zSkAL00V6LSrrLZ3QicZM8HAoWQQ78IFdechMPfa/FgHvrxFbIzOdXo2xndy8mUw8="
  app:
    production: csmock
  on:
    repo: sh19910711/cs-mock
